<script setup lang="ts">
const { filaments, printers, products, marketplaces, settings, listCalculatorSimulations, createCalculatorSimulation } = useAppData()
const { notify } = useUi()
const route = useRoute()
import { calculatePricing } from '../utils/pricing.js'
const productId = ref(''), filamentId = ref(''), printerId = ref('')
const simulationName = ref('')
const priceKg = ref(100), weight = ref(150), wastePercent = ref(0), hours = ref(6), minutes = ref(0)
const energyEnabled = ref(true), energyRate = ref(0.68), watts = ref(110)
const marketplaceSource = ref('manual'), marketplaceName = ref('')
const packaging = ref(0), materials = ref(0), labor = ref(0), otherCosts = ref(0), marketplaceFee = ref(0), taxPercent = ref(0), desiredMargin = ref(40)
const salePrice = ref(0)
const errors = reactive<Record<string, string>>({})
const simulations = ref<any[]>([])
const historyLoading = ref(false)
const selectedProduct = computed(() => products.value.find(product => String(product.id || '') === productId.value))
const preferences = computed(() => (settings.value?.preferences || {}) as Record<string, unknown>)
const fixedCostPerUnit = computed(() => { const fixed = Number(preferences.value.monthlyFixedCost || 0); const planned = Number(preferences.value.plannedMonthlyUnits || 0); return planned > 0 ? fixed / planned : 0 })
const selectedFilament = computed(() => filaments.value.find(filament => String(filament.id || '') === filamentId.value))
const selectedPrinter = computed(() => printers.value.find(printer => String(printer.id || '') === printerId.value))
const selectedMarketplace = computed(() => marketplaces.value.find(marketplace => marketplace.name === marketplaceName.value))
const channelFee = computed(() => selectedMarketplace.value ? Number(selectedMarketplace.value.commission || 0) + Number(selectedMarketplace.value.financial || 0) + Number(selectedMarketplace.value.ads || 0) + Number(selectedMarketplace.value.others || 0) : 0)
const effectiveMarketplaceFee = computed(() => marketplaceSource.value === 'channel' ? channelFee.value : Number(marketplaceFee.value || 0))
const effectiveMarketplaceFixedFee = computed(() => marketplaceSource.value === 'channel' ? Number(selectedMarketplace.value?.fixed || 0) : 0)
const pricing = computed(() => calculatePricing({ pricePerKg: priceKg.value, weight: weight.value, wastePercent: wastePercent.value, hours: hours.value, minutes: minutes.value, energyEnabled: energyEnabled.value, energyRate: energyRate.value, watts: watts.value, fixedCostPerUnit: fixedCostPerUnit.value, packaging: packaging.value, materials: materials.value, labor: labor.value, otherCosts: otherCosts.value, marketplaceFee: effectiveMarketplaceFee.value, marketplaceFixedFee: effectiveMarketplaceFixedFee.value, taxPercent: taxPercent.value, desiredMargin: desiredMargin.value, salePrice: salePrice.value }))
const duration = computed(() => pricing.value.durationMinutes / 60), effectiveWeight = computed(() => pricing.value.effectiveWeight), costGram = computed(() => Math.max(0, Number(priceKg.value || 0)) / 1000), filamentCost = computed(() => pricing.value.materialCost), energyCost = computed(() => pricing.value.energyCost), baseCost = computed(() => pricing.value.baseCost), feeRate = computed(() => pricing.value.feeRate), priceDenominator = computed(() => pricing.value.denominator), suggestedPrice = computed(() => pricing.value.suggestedPrice), feeCost = computed(() => pricing.value.feeCost), totalCost = computed(() => pricing.value.totalCost), estimatedProfit = computed(() => pricing.value.profit), actualMargin = computed(() => pricing.value.margin)
const viability = computed(() => priceDenominator.value <= 0 ? { title: 'Parâmetros inviáveis', text: 'A margem desejada somada às taxas precisa ser menor que 100%.', state: 'bad' } : actualMargin.value >= 40 ? { title: 'Peça viável', text: 'O preço cobre os custos completos, as taxas e a margem desejada.', state: 'good' } : actualMargin.value >= 20 ? { title: 'Margem de atenção', text: 'A simulação é possível, mas revise os custos antes de vender.', state: 'warn' } : { title: 'Margem baixa', text: 'Revise o preço ou os custos para proteger a rentabilidade.', state: 'bad' })
const clearErrors = () => Object.keys(errors).forEach(key => delete errors[key])
const validate = () => { clearErrors(); if (priceKg.value < 0) errors.priceKg = 'Informe um preço válido.'; if (weight.value <= 0) errors.weight = 'Informe o peso da peça.'; if (hours.value < 0 || minutes.value < 0 || minutes.value > 59) errors.duration = 'Informe um tempo válido.'; if (energyEnabled.value && (energyRate.value < 0 || watts.value < 0)) errors.energy = 'Informe energia e potência válidas.'; if (wastePercent.value < 0) errors.waste = 'A perda não pode ser negativa.'; if (marketplaceSource.value === 'channel' && !selectedMarketplace.value) errors.fees = 'Selecione um canal cadastrado.'; if (marketplaceSource.value === 'manual' && marketplaceFee.value < 0 || taxPercent.value < 0) errors.fees = 'Informe taxas válidas.'; if (desiredMargin.value < 0 || desiredMargin.value >= 100 - feeRate.value * 100) errors.margin = 'A margem deve deixar espaço para as taxas.'; return !Object.keys(errors).length }
const applyProduct = (product: any) => { if (!product) return; weight.value = Number(product.weight || weight.value); const time = String(product.time || '').match(/(\d+(?:[.,]\d+)?)\s*h(?:\s*(\d+(?:[.,]\d+)?)\s*m)?/i); if (time) { hours.value = Number(time[1].replace(',', '.')); minutes.value = Number((time[2] || 0).replace(',', '.')) }; printerId.value = String(product.printerId || ''); filamentId.value = String(product.filamentId || ''); packaging.value = Number(product.packaging || 0); materials.value = Number(product.materials || 0); labor.value = Number(product.labor || 0); otherCosts.value = Number(product.costBreakdown?.otherCosts || 0); marketplaceFee.value = Number(product.marketplaceFee || 0); desiredMargin.value = Number(product.desiredMargin || preferences.value.defaultMargin || 40) }
watch(productId, value => applyProduct(products.value.find(product => String(product.id || '') === value)))
watch(filamentId, value => { const filament = filaments.value.find(item => String(item.id || '') === value); if (filament?.initial) priceKg.value = round2(Number(filament.cost || 0) / Number(filament.initial) * 1000) })
watch(printerId, value => { const printer = printers.value.find(item => String(item.id || '') === value); if (printer?.power) watts.value = Number(printer.power) })
watch(() => settings.value, value => { if (!value) return; energyRate.value = Number(value.kwh || 0.68); if (desiredMargin.value === 40) desiredMargin.value = Number(preferences.value.defaultMargin || 40) }, { immediate: true })
const simulation = computed(() => ({ productId: productId.value, productName: selectedProduct.value?.name || '', filamentId: filamentId.value, printerId: printerId.value, priceKg: priceKg.value, weight: weight.value, wastePercent: wastePercent.value, hours: hours.value, minutes: minutes.value, energyEnabled: energyEnabled.value, energyRate: energyRate.value, watts: watts.value, packaging: packaging.value, materials: materials.value, labor: labor.value, otherCosts: otherCosts.value, marketplaceSource: marketplaceSource.value, marketplaceName: marketplaceName.value, marketplaceFee: effectiveMarketplaceFee.value, marketplaceFixedFee: effectiveMarketplaceFixedFee.value, taxPercent: taxPercent.value, desiredMargin: desiredMargin.value, baseCost: baseCost.value, totalCost: totalCost.value, suggestedPrice: suggestedPrice.value, profit: estimatedProfit.value, margin: actualMargin.value, savedAt: new Date().toISOString() }))
const saveSimulation = async () => {
  if (!validate()) return notify('Revise os campos destacados.', 'info')
  try {
    const saved = await createCalculatorSimulation({ name: simulationName.value.trim() || selectedProduct.value?.name || 'Simulação sem nome', pricePerKg: priceKg.value, weight: weight.value, durationMinutes: Math.round(duration.value * 60), energyEnabled: energyEnabled.value, energyRate: energyRate.value, watts: watts.value, margin: desiredMargin.value, directCost: totalCost.value, suggestedPrice: suggestedPrice.value, snapshot: simulation.value })
    simulations.value = [saved, ...simulations.value.filter(item => item.id !== saved.id)].slice(0, 20)
    if (import.meta.client) sessionStorage.setItem('printflow-calculator-simulation', JSON.stringify(simulation.value))
    notify('Simulação salva no histórico.')
  } catch (error: any) { notify(error?.data?.error || error?.message || 'Não foi possível salvar a simulação.', 'info') }
}
const loadSimulation = (item: any) => {
  const draft = item?.snapshot || item
  simulationName.value = item?.name || ''
  productId.value = draft.productId || ''
  filamentId.value = draft.filamentId || ''
  printerId.value = draft.printerId || ''
  priceKg.value = Number(draft.priceKg ?? item.pricePerKg ?? priceKg.value); weight.value = Number(draft.weight ?? item.weight ?? weight.value); wastePercent.value = Number(draft.wastePercent || 0)
  hours.value = Math.floor(Number(draft.hours ?? item.durationMinutes / 60 ?? hours.value)); minutes.value = Number(draft.minutes ?? (item.durationMinutes || 0) % 60)
  energyEnabled.value = draft.energyEnabled !== false; energyRate.value = Number(draft.energyRate ?? item.energyRate ?? energyRate.value); watts.value = Number(draft.watts ?? item.watts ?? watts.value)
  packaging.value = Number(draft.packaging || 0); materials.value = Number(draft.materials || 0); labor.value = Number(draft.labor || 0); otherCosts.value = Number(draft.otherCosts || 0); marketplaceSource.value = draft.marketplaceSource || 'manual'; marketplaceName.value = draft.marketplaceName || ''; marketplaceFee.value = Number(draft.marketplaceFee || 0); taxPercent.value = Number(draft.taxPercent || 0); desiredMargin.value = Number(draft.desiredMargin ?? item.margin ?? desiredMargin.value)
}
const createProduct = () => { if (!validate()) return notify('Revise os campos destacados.', 'info'); if (import.meta.client) sessionStorage.setItem('printflow-calculator-draft', JSON.stringify(simulation.value)); navigateTo('/produtos/novo?from=calculator') }
onMounted(async () => { const queryProduct = String(route.query.productId || ''); if (queryProduct) productId.value = queryProduct; historyLoading.value = true; try { simulations.value = await listCalculatorSimulations() } catch { simulations.value = [] } finally { historyLoading.value = false } })
</script>
<template>
  <div><PageHeader title="Calculadora 3D" subtitle="Calcule o custo completo e o preço mínimo rentável de uma peça." icon="calculator"/>
    <div class="calculator-layout"><div>
      <div class="form-card"><h2 class="form-card__title"><UiIcon name="box"/>Base da simulação</h2><div class="form-grid"><div class="field col-12"><label>Nome da simulação</label><input v-model="simulationName" maxlength="160" placeholder="Ex.: Vaso grande PLA preto"></div><div class="field col-12"><label>Produto cadastrado (opcional)</label><select v-model="productId"><option value="">Simulação manual</option><option v-for="product in products" :key="product.id" :value="product.id">{{product.name}} · {{product.sku}}</option></select><small>Ao selecionar, os dados da receita e custos são preenchidos.</small></div><div class="field col-6"><label>Filamento</label><select v-model="filamentId"><option value="">Informar preço manualmente</option><option v-for="filament in filaments" :key="filament.id" :value="filament.id">{{filament.name}} · {{filament.material}}</option></select></div><div class="field col-6"><label>Impressora</label><select v-model="printerId"><option value="">Informar potência manualmente</option><option v-for="printer in printers" :key="printer.id" :value="printer.id">{{printer.name}} · {{printer.power}} W</option></select></div></div></div>
      <div class="form-card"><h2 class="form-card__title"><UiIcon name="spool"/>Material</h2><div class="form-grid"><div class="field col-6" :class="{'field--error':errors.priceKg}"><label>Preço do quilo (R$)</label><input v-model.number="priceKg" type="number" min="0" step=".01"><small v-if="errors.priceKg" class="field__error">{{errors.priceKg}}</small></div><div class="field col-3" :class="{'field--error':errors.weight}"><label>Peso (g)</label><input v-model.number="weight" type="number" min="0" step=".1"><small v-if="errors.weight" class="field__error">{{errors.weight}}</small></div><div class="field col-3" :class="{'field--error':errors.waste}"><label>Perdas (%)</label><input v-model.number="wastePercent" type="number" min="0" step=".1"><small v-if="errors.waste" class="field__error">{{errors.waste}}</small></div><div class="stat-box col-12"><small>Custo por grama: <strong>{{formatCurrency(costGram)}}</strong> · Material considerado: <strong>{{effectiveWeight.toFixed(1)}} g</strong></small></div></div></div>
      <div class="form-card"><h2 class="form-card__title"><UiIcon name="clock"/>Produção e energia</h2><div class="form-grid"><div class="field col-3" :class="{'field--error':errors.duration}"><label>Horas</label><input v-model.number="hours" type="number" min="0"></div><div class="field col-3"><label>Minutos</label><input v-model.number="minutes" type="number" min="0" max="59"><small v-if="errors.duration" class="field__error">{{errors.duration}}</small></div><div class="field col-6"><label>Considerar energia?</label><button type="button" class="switch" :class="{active:energyEnabled}" @click="energyEnabled=!energyEnabled"/></div><div v-if="energyEnabled" class="field col-6" :class="{'field--error':errors.energy}"><label>Custo do kWh (R$)</label><input v-model.number="energyRate" type="number" min="0" step=".01"></div><div v-if="energyEnabled" class="field col-6"><label>Potência média (W)</label><input v-model.number="watts" type="number" min="0"><small v-if="errors.energy" class="field__error">{{errors.energy}}</small></div></div></div>
      <div class="form-card"><h2 class="form-card__title"><UiIcon name="money"/>Custos adicionais e taxas</h2><div class="form-grid"><div class="field col-3"><label>Embalagem (R$)</label><input v-model.number="packaging" type="number" min="0" step=".01"></div><div class="field col-3"><label>Materiais (R$)</label><input v-model.number="materials" type="number" min="0" step=".01"></div><div class="field col-3"><label>Mão de obra (R$)</label><input v-model.number="labor" type="number" min="0" step=".01"></div><div class="field col-3"><label>Outros custos (R$)</label><input v-model.number="otherCosts" type="number" min="0" step=".01"></div><div class="field col-6"><label>Fonte das taxas</label><select v-model="marketplaceSource"><option value="manual">Informar manualmente</option><option value="channel" :disabled="!marketplaces.length">Canal cadastrado</option></select></div><div v-if="marketplaceSource === 'channel'" class="field col-6"><label>Canal</label><select v-model="marketplaceName"><option value="">Selecione um canal</option><option v-for="marketplace in marketplaces" :key="marketplace.id || marketplace.name" :value="marketplace.name">{{marketplace.name}}</option></select><small>{{effectiveMarketplaceFee.toFixed(1)}}% + {{formatCurrency(effectiveMarketplaceFixedFee)}} fixos</small></div><div v-else class="field col-6"><label>Taxas marketplace (%)</label><input v-model.number="marketplaceFee" type="number" min="0" step=".1"></div><div class="field col-6"><label>Impostos (%)</label><input v-model.number="taxPercent" type="number" min="0" step=".1"><small v-if="errors.fees" class="field__error">{{errors.fees}}</small></div></div></div>
      <div class="form-card"><h2 class="form-card__title"><UiIcon name="target"/>Margem desejada</h2><div class="form-grid"><div class="field col-6" :class="{'field--error':errors.margin}"><label>Margem sobre o preço (%)</label><input v-model.number="desiredMargin" type="number" min="0" max="99" step=".1"><small>Margem = lucro ÷ preço de venda.</small><small v-if="errors.margin" class="field__error">{{errors.margin}}</small></div><div class="info-note col-6"><UiIcon name="info" :size="17"/>Custos fixos rateados: {{formatCurrency(fixedCostPerUnit)}} por unidade.</div></div></div>
      <div class="form-grid" style="margin-bottom:12px"><div class="field col-6" :class="{'field--error':errors.salePrice}"><label>Preço praticado (R$)</label><input v-model.number="salePrice" type="number" min="0" step=".01" placeholder="Usar preço sugerido"><small>Zero usa o preço sugerido automaticamente.</small><small v-if="errors.salePrice" class="field__error">{{errors.salePrice}}</small></div><div class="info-note col-6"><UiIcon name="info" :size="17"/>O resultado ao lado mostra lucro e margem no preço praticado.</div></div>
      <div class="calculator-actions"><button class="btn btn--primary" @click="validate() ? notify('Simulação validada com sucesso.') : notify('Revise os campos destacados.', 'info')"><UiIcon name="calculator"/>Validar cálculo</button><button class="btn" @click="saveSimulation"><UiIcon name="save"/>Salvar no histórico</button></div>
      <div class="form-card simulation-history"><h2 class="form-card__title"><UiIcon name="clock"/>Histórico de simulações</h2><div v-if="historyLoading" class="empty-state">Carregando histórico...</div><div v-else-if="!simulations.length" class="empty-state"><div><h3>Nenhuma simulação salva</h3><p>Salve uma simulação para recuperá-la depois.</p></div></div><div v-else><button v-for="item in simulations" :key="item.id" type="button" class="simulation-history__row" @click="loadSimulation(item)"><span><strong>{{item.name}}</strong><small>{{new Date(item.createdAt).toLocaleString('pt-BR')}}</small></span><span><strong>{{formatCurrency(item.suggestedPrice)}}</strong><small>{{Number(item.margin).toFixed(1)}}% de margem</small></span></button></div></div>
    </div><div class="calculator-results"><div class="calculator-results__head"><UiIcon name="trend" :size="34"/><div><h2>Resultado da Simulação</h2><p>Composição completa do custo e preço mínimo sugerido.</p></div></div><div class="result-grid"><div class="result-card"><div class="result-card__label"><UiIcon name="spool"/>Material + perdas</div><strong>{{formatCurrency(filamentCost)}}</strong><small>{{effectiveWeight.toFixed(1)}} g × {{formatCurrency(costGram)}}/g</small></div><div class="result-card"><div class="result-card__label"><UiIcon name="bolt"/>Energia</div><strong>{{formatCurrency(energyCost)}}</strong><small>{{energyEnabled ? `${(watts / 1000 * duration).toFixed(2)} kWh × ${formatCurrency(energyRate)}` : 'Não considerada'}}</small></div><div class="result-card"><div class="result-card__label"><UiIcon name="money"/>Custos adicionais</div><strong>{{formatCurrency(baseCost - filamentCost - energyCost)}}</strong><small>Fixos, embalagem, mão de obra e outros</small></div><div class="result-card result-card--blue"><div class="result-card__label"><UiIcon name="wallet"/>Custo total</div><strong>{{formatCurrency(totalCost)}}</strong><small>Inclui taxas e impostos</small></div><div class="result-card result-card--purple"><div class="result-card__label"><UiIcon name="percent"/>Margem real</div><strong>{{actualMargin.toFixed(1)}}%</strong><small>Lucro ÷ preço sugerido</small></div><div class="result-card result-card--highlight"><div class="result-card__label"><UiIcon name="tag"/>Preço sugerido</div><strong>{{formatCurrency(suggestedPrice)}}</strong><small>Margem desejada: {{desiredMargin}}%</small></div></div><div class="summary-box"><div class="detail-list__row"><span>Taxas e impostos</span><strong>{{formatCurrency(feeCost)}}</strong></div><div class="detail-list__row"><span>Lucro estimado</span><strong class="money-positive">{{formatCurrency(estimatedProfit)}}</strong></div></div><div class="viability" :style="viability.state==='warn'?{borderColor:'#f5a623',color:'#b66808',background:'#fffaf0'}:viability.state==='bad'?{borderColor:'#ef4444',color:'#c12c35',background:'#fff5f5'}:{}"><span class="viability__icon"><UiIcon :name="viability.state==='good'?'check':'alert'"/></span><div><h3>{{viability.title}}</h3><p>{{viability.text}}</p></div></div><button class="btn btn--success btn--wide" style="margin-top:14px" @click="createProduct"><UiIcon name="box"/>Criar produto com esta simulação</button></div></div>
  </div>
</template>
<style scoped>.calculator-actions{display:flex;gap:10px;margin-top:12px}.calculator-actions .btn{flex:1}.field small{display:block;margin-top:4px;color:var(--muted);font-size:9px}.field__error{color:var(--danger)!important}.simulation-history{margin-top:12px}.simulation-history__row{display:flex;justify-content:space-between;align-items:center;gap:12px;width:100%;padding:10px 0;border:0;border-bottom:1px solid #edf1f6;background:transparent;color:inherit;text-align:left;cursor:pointer}.simulation-history__row:last-child{border-bottom:0}.simulation-history__row:hover strong{color:var(--blue)}.simulation-history__row strong,.simulation-history__row small{display:block}.simulation-history__row small{margin-top:3px;color:var(--muted);font-size:9px}@media(max-width:700px){.calculator-actions{flex-direction:column}}</style>
