<script setup lang="ts">
const { notify } = useUi()
const active = ref('Empresa')
const tabs=[['Empresa','building','Informacoes da empresa'],['Financeiro','money','Impostos, moedas e contas'],['Usuarios e Permissoes','users','Gestao de usuarios e acessos'],['Notificacoes','bell','E-mails e alertas do sistema'],['Seguranca','shield','Acesso, 2FA e sessoes'],['Personalizacao','settings','Marca, aparencia e preferencias'],['Integracoes','box','Marketplaces e servicos'],['Backup e Dados','download','Exportar e restaurar dados']]
const company=reactive({name:'',cnpj:'',phone:'',email:'',address:'',district:'',city:'',state:'',zip:'',country:'Brasil',currency:'Real (R$)',timezone:'(GMT-03:00) Brasilia',kwh:0})
</script>
<template>
  <div><PageHeader title="Configuracoes" subtitle="Gerencie as configuracoes da sua empresa e da plataforma"/>
    <div class="settings-layout"><nav class="settings-nav"><button v-for="t in tabs" :key="t[0]" :class="{active:active===t[0]}" @click="active=t[0]"><span class="settings-nav__icon"><UiIcon :name="t[1]"/></span><span><strong>{{t[0]}}</strong><small>{{t[2]}}</small></span></button></nav>
      <section class="settings-panel"><div v-if="active==='Empresa'"><div style="display:flex;justify-content:space-between;gap:12px"><div><h2>Informacoes da Empresa</h2><p>Atualize os dados principais da sua empresa.</p></div><button class="btn btn--primary" @click="notify('Alteracoes salvas com sucesso')">Salvar alteracoes</button></div><div class="form-grid"><div class="field col-7"><label>Nome da Empresa *</label><input v-model="company.name"></div><div class="field col-5"><label>CNPJ *</label><input v-model="company.cnpj"></div><div class="field col-6"><label>Telefone</label><input v-model="company.phone"></div><div class="field col-6"><label>E-mail *</label><input v-model="company.email"></div><div class="field col-8"><label>Endereco *</label><input v-model="company.address"></div><div class="field col-4"><label>Bairro</label><input v-model="company.district"></div><div class="field col-4"><label>Cidade *</label><input v-model="company.city"></div><div class="field col-2"><label>Estado *</label><input v-model="company.state"></div><div class="field col-3"><label>CEP *</label><input v-model="company.zip"></div><div class="field col-3"><label>Pais *</label><input v-model="company.country"></div><div class="field col-4"><label>Moeda</label><input v-model="company.currency"></div><div class="field col-4"><label>Fuso Horario</label><input v-model="company.timezone"></div><div class="field col-4"><label>Custo medio do kWh</label><input v-model.number="company.kwh" type="number" step=".01"></div><div class="field col-12"><label>Logotipo da Empresa</label><div class="info-note" style="align-items:center;justify-content:center;min-height:90px"><AppLogo/><span>Clique ou arraste o arquivo aqui</span></div></div></div></div><div v-else class="empty-state"><div><div class="empty-state__icon"><UiIcon :name="tabs.find(x=>x[0]===active)?.[1] || 'settings'" :size="29"/></div><h3>{{active}}</h3><p>Este modulo visual esta preparado para receber as configuracoes correspondentes quando conectado a API.</p><button class="btn btn--primary" @click="notify('Preferencias atualizadas')">Salvar preferencias</button></div></div></section>
      <aside class="settings-panel"><h2>LGPD e Isolamento de Dados</h2><p>Seus dados estao seguros e em conformidade com a legislacao.</p><ul class="check-list"><li><span><UiIcon name="check" :size="15"/></span>Seus dados sao armazenados com criptografia de ponta a ponta.</li><li><span><UiIcon name="check" :size="15"/></span>Backups diarios realizados em ambiente seguro.</li><li><span><UiIcon name="check" :size="15"/></span>Isolamento total entre contas e empresas.</li><li><span><UiIcon name="check" :size="15"/></span>Conformidade com a Lei Geral de Protecao de Dados.</li></ul><button class="btn btn--wide" @click="notify('Solicitacao de exportacao registrada')"><UiIcon name="download"/>Solicitar exportacao dos dados</button></aside></div>
    <PanelCard title="Funcoes de Usuario" subtitle="Defina as funcoes disponiveis e o nivel de acesso de cada uma." style="margin-top:12px"><div class="role-grid"><div v-for="(r,i) in [{n:'Administrador',d:'Acesso total a todas as areas da plataforma.',u:2},{n:'Financeiro',d:'Gerencia financas, vendas, despesas e relatorios.',u:3},{n:'Producao',d:'Gerencia producao, impressoras e estoque.',u:4},{n:'Operador',d:'Acesso basico para operacao do dia a dia.',u:6}]" :key="r.n" class="role-card"><div class="role-card__icon" :style="i===1?{color:'#0da566',background:'#eaf9f1'}:i===2?{color:'#f57c1f',background:'#fff3e9'}:i===3?{color:'#1768f2',background:'#eef5ff'}:{}"><UiIcon :name="i===0?'shield':i===1?'money':i===2?'box':'users'"/></div><h3>{{r.n}}</h3><p>{{r.d}}</p><span class="badge">{{r.u}} usuarios</span></div></div></PanelCard>
  </div>
</template>
