<script setup lang="ts">
const { expenses, expenseSegments } = useAppData()
const search = ref('')
const category = ref('Todas')
const filtered = computed(() => expenses.value.filter(e => (category.value === 'Todas' || e.category === category.value) && Object.values(e).join(' ').toLowerCase().includes(search.value.toLowerCase())))
const goToNewExpense = () => navigateTo('/despesas/nova')
</script>
<template>
  <div>
    <PageHeader title="Despesas" subtitle="Acompanhe e gerencie todos os gastos do seu negocio de impressao 3D." />
    <div class="metrics-grid metrics-grid--4"><MetricCard label="Despesas Totais" value="R$ 9.320,00" icon="receipt" change="8,6%" note="vs. mes anterior" color="red" negative/><MetricCard label="Despesas Recorrentes" value="R$ 4.250,00" icon="calendar" change="45,6% do total" note="vs. mes anterior" color="orange"/><MetricCard label="Maior Categoria" value="Filamento" icon="tag" change="R$ 3.420,00" note="36,7% do total" color="purple"/><MetricCard label="Media Mensal" value="R$ 9.125,00" icon="chart" change="4,2%" note="vs. ultimos 3 meses" color="cyan"/></div>
    <div class="filters"><div class="field field--search"><label>Buscar</label><div class="search-field"><UiIcon name="search" :size="16"/><input v-model="search" placeholder="Descricao ou fornecedor"></div></div><div class="field"><label>Categoria</label><select v-model="category"><option>Todas</option><option v-for="c in [...new Set(expenses.map(x=>x.category))]" :key="c">{{c}}</option></select></div><div class="field"><label>Forma de pagamento</label><select><option>Todas</option><option>PIX</option><option>Cartao</option><option>Boleto</option></select></div><button class="btn" @click="search='';category='Todas'"><UiIcon name="close" :size="15"/> Limpar</button><button class="btn btn--primary filters__push" type="button" @click="goToNewExpense"><UiIcon name="plus" :size="16"/> Nova Despesa</button></div>
    <div class="split-layout" style="grid-template-columns:minmax(0,1fr) 350px"><PanelCard title="Lista de Despesas"><div class="table-scroll"><table class="data-table"><thead><tr><th>Descricao</th><th>Categoria</th><th>Fornecedor</th><th>Valor</th><th>Data</th><th>Pagamento</th><th>Recorrencia</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="e in filtered" :key="e.description"><td><strong>{{e.description}}</strong></td><td><span class="badge">{{e.category}}</span></td><td>{{e.supplier}}</td><td><strong>{{formatCurrency(e.value)}}</strong></td><td>{{e.date}}</td><td>{{e.payment}}</td><td>{{e.recurrence}}</td><td><span class="badge badge--green">{{e.status}}</span></td><td><button class="row-action"><UiIcon name="more" :size="16"/></button></td></tr></tbody></table></div><div class="table-footer"><span>Mostrando 1 a {{filtered.length}} de 24 despesas</span><div class="pagination"><button class="page-btn active">1</button><button class="page-btn">2</button><button class="page-btn">3</button></div></div></PanelCard><aside><PanelCard title="Despesas por Categoria"><DonutChart :segments="expenseSegments" total="R$ 9.320"/></PanelCard><PanelCard title="Proximas Despesas Recorrentes" style="margin-top:12px"><div class="alerts-list"><div v-for="(item,i) in [{n:'Conta de Energia (Enel)',v:1180,d:'Em 29 dias'},{n:'Assinatura Fusion 360',v:210,d:'Em 24 dias'},{n:'Taxa Mercado Livre',v:740,d:'Em 23 dias'}]" :key="item.n" class="alert-row"><span class="alert-row__icon"><UiIcon :name="i===0?'bolt':'receipt'" :size="17"/></span><div><strong>{{item.n}}</strong><small>Vencimento em junho</small></div><strong>{{formatCurrency(item.v)}}</strong><span class="badge badge--orange">{{item.d}}</span></div></div><div class="summary-box"><div class="detail-list__row"><span>Total proximos 30 dias</span><strong class="money-positive">R$ 2.130,00</strong></div></div></PanelCard></aside></div>
  </div>
</template>
