<script setup lang="ts">
const { products, expenseSegments } = useAppData()
const metrics = useBusinessMetrics()
const { notify } = useUi()
const revenue=[2,6,3,5,2.5,5,6.5,5.8,8,6.5,8.2,5.5,6,3.6,4.5,7,5.8]
const expenses=[1,1.4,2.5,1.5,1,2.2,3.2,2.1,2.7,2,3.7,2.5,3.2,2,2.9,2.3,4.4,3.9]
const labels=['01/05','','04/05','','07/05','','10/05','','13/05','','16/05','','19/05','','22/05','','25/05']
</script>
<template>
  <div><PageHeader title="Relatorios" subtitle="Analises detalhadas para impulsionar o crescimento do seu negocio."><button class="btn" @click="notify('Relatorio preparado para exportacao')"><UiIcon name="download"/>Exportar</button></PageHeader>
    <div class="filters"><div class="field"><label>Periodo</label><input value="01/05/2024 - 31/05/2024"></div><div class="field"><label>Agrupamento</label><select><option>Diario</option><option>Semanal</option><option>Mensal</option></select></div><div v-for="f in ['Marketplace','Produto','Categoria','Impressora']" :key="f" class="field"><label>{{f}}</label><select><option>Todos</option></select></div></div>
    <div class="metrics-grid metrics-grid--5"><MetricCard label="Faturamento" :value="formatCurrency(metrics.revenue.value)" icon="trend" note="Dados do banco"/><MetricCard label="Lucro Liquido" :value="formatCurrency(metrics.profit.value)" icon="money" note="Dados do banco" color="green"/><MetricCard label="Margem Liquida" :value="metrics.percent(metrics.margin.value)" icon="percent" note="Dados do banco" color="green"/><MetricCard label="Ticket Medio" :value="formatCurrency(metrics.ticket.value)" icon="tag" note="Dados do banco" color="orange"/><MetricCard label="Quantidade de Pedidos" :value="formatNumber(metrics.orderCount.value)" icon="bag" note="Dados do banco" color="purple"/></div>
    <div class="dashboard-grid" style="grid-template-columns:1fr 1fr 1fr 1fr"><PanelCard title="Faturamento"><LineChart :values="revenue" :labels="labels"/></PanelCard><PanelCard title="Despesas"><LineChart :values="expenses" :labels="labels" color="#ef4444"/></PanelCard><PanelCard title="Receita x Despesas"><LineChart :values="revenue" :second="expenses" :labels="labels"/></PanelCard><PanelCard title="Lucro Liquido"><LineChart :values="revenue.map((x,i)=>x-expenses[i]+2)" :labels="labels" color="#0da566"/></PanelCard></div>
    <div class="dashboard-grid" style="grid-template-columns:.8fr 1.2fr"><PanelCard title="Despesas por Categoria"><DonutChart :segments="expenseSegments" :total="formatCurrency(metrics.expenseTotal.value)"/></PanelCard><PanelCard title="Faturamento por Marketplace"><div class="bar-list" style="padding:20px"><div v-for="(x,i) in [{n:'Shopee',v:8250},{n:'Mercado Livre',v:6120},{n:'Site Proprio',v:2980},{n:'Instagram',v:1100}]" :key="x.n" class="bar-row"><span>{{x.n}}</span><div class="bar-row__track"><div class="bar-row__fill" :style="{width:`${x.v/8250*100}%`,background:['#1768f2','#3778df','#5791e8','#79aaf0'][i]}"/></div><strong>{{formatCurrency(x.v)}}</strong></div></div></PanelCard></div>
    <div class="dashboard-grid"><PanelCard title="Produtos mais vendidos"><div class="table-scroll"><table class="data-table"><thead><tr><th>#</th><th>Produto</th><th>Qtd.</th><th>Faturamento</th></tr></thead><tbody><tr v-for="(p,i) in products" :key="p.sku"><td><strong>{{i+1}}</strong></td><td><div class="table-product"><ProductThumb :type="p.thumb" :size="25"/>{{p.name}}</div></td><td>{{[58,42,36,31,26][i]}}</td><td>{{formatCurrency([2900,2100,1800,1550,988][i])}}</td></tr></tbody></table></div></PanelCard><PanelCard title="Produtos mais lucrativos"><div class="table-scroll"><table class="data-table"><thead><tr><th>#</th><th>Produto</th><th>Lucro Liquido</th><th>Margem</th></tr></thead><tbody><tr v-for="(p,i) in products" :key="p.sku"><td><strong>{{i+1}}</strong></td><td>{{p.name}}</td><td>{{formatCurrency([1740,1220,1080,930,567][i])}}</td><td><span class="badge badge--green">{{[60,58.1,60,60,57.4][i]}}%</span></td></tr></tbody></table></div></PanelCard><PanelCard title="Produtos com melhor margem"><div class="table-scroll"><table class="data-table"><thead><tr><th>#</th><th>Produto</th><th>Margem</th></tr></thead><tbody><tr v-for="(p,i) in products" :key="p.sku"><td><strong>{{i+1}}</strong></td><td>{{p.name}}</td><td class="money-positive">{{[72.3,69.2,66.7,64.8,63.9][i]}}%</td></tr></tbody></table></div></PanelCard></div>
  </div>
</template>
