<script setup lang="ts">
const { filaments, products, loadInventoryOverview, createProductInventoryMovement, refreshAppData } = useAppData()
const { notify } = useUi()
const route = useRoute()
const loading = ref(true)
const saving = ref(false)
const inventory = ref<any>({ products: [], movements: [] })
const selectedProductId = ref('')
const movement = reactive({ type: 'in' as 'in' | 'out' | 'adjustment', quantity: 0, reason: '' })
const section = computed(() => String(route.query.secao || 'visao'))
const selectedProduct = computed(() => inventory.value.products.find((item: any) => String(item.id) === selectedProductId.value) || inventory.value.products[0])
const productMovements = computed(() => inventory.value.movements.filter((item: any) => item.resource === 'products'))
const totalFilamentWeight = computed(() => filaments.value.reduce((sum, item: any) => sum + Number(item.remaining || 0), 0))
const totalProductUnits = computed(() => inventory.value.products.reduce((sum: number, item: any) => sum + Number(item.quantity || 0), 0))
const reservedProductUnits = computed(() => inventory.value.products.reduce((sum: number, item: any) => sum + Number(item.reservedQuantity || 0), 0))
const lowFilaments = computed(() => filaments.value.filter((item: any) => Number(item.remaining || 0) <= Number(item.minStock ?? 300)))
const refresh = async () => {
  loading.value = true
  try { inventory.value = await loadInventoryOverview() } catch (error: any) { notify(error?.data?.error || error?.message || 'Não foi possível carregar o estoque.', 'info') } finally { loading.value = false }
}
const saveMovement = async () => {
  const product = selectedProduct.value
  if (!product?.id || saving.value || movement.quantity <= 0 || !movement.reason.trim()) return notify('Informe quantidade e motivo da movimentação.', 'info')
  saving.value = true
  try {
    await createProductInventoryMovement(String(product.id), { ...movement })
    movement.quantity = 0; movement.reason = ''
    await refresh(); await refreshAppData(true)
    notify('Movimentação registrada e estoque atualizado.')
  } catch (error: any) { notify(error?.data?.error || error?.message || 'Não foi possível registrar a movimentação.', 'info') } finally { saving.value = false }
}
watch(() => inventory.value.products, (list) => { if (!list.some((item: any) => String(item.id) === selectedProductId.value)) selectedProductId.value = list[0] ? String(list[0].id) : '' }, { immediate: true })
onMounted(refresh)
</script>

<template>
  <div>
    <PageHeader title="Estoque e Produção" subtitle="Acompanhe materiais, produtos fabricados e cada movimentação do seu estoque."><NuxtLink class="btn btn--primary" to="/filamentos/novo"><UiIcon name="plus" :size="16" />Cadastrar filamento</NuxtLink></PageHeader>
    <div class="stock-tabs" role="tablist" aria-label="Seções do estoque"><NuxtLink to="/estoque?secao=visao" :class="{active:section==='visao'}">Visão geral</NuxtLink><NuxtLink to="/estoque?secao=filamentos" :class="{active:section==='filamentos'}">Filamentos</NuxtLink><NuxtLink to="/estoque?secao=produtos" :class="{active:section==='produtos'}">Produtos fabricados</NuxtLink><NuxtLink to="/estoque?secao=movimentacoes" :class="{active:section==='movimentacoes'}">Movimentações</NuxtLink></div>
    <div v-if="loading" class="empty-state stock-loading">Carregando estoque...</div>
    <template v-else>
      <div v-if="section==='visao'" class="stock-overview">
        <div class="metrics-grid metrics-grid--4"><MetricCard label="Filamento disponível" :value="`${formatNumber(totalFilamentWeight / 1000)} kg`" icon="spool" note="Saldo atual" color="purple" /><MetricCard label="Produtos prontos" :value="formatNumber(totalProductUnits)" icon="box" note="Unidades fabricadas" color="green" /><MetricCard label="Itens reservados" :value="formatNumber(reservedProductUnits)" icon="target" note="Separados para venda" color="blue" /><MetricCard label="Alertas de reposição" :value="formatNumber(lowFilaments.length)" icon="alert" note="Filamentos abaixo do mínimo" color="orange" /></div>
        <div class="dashboard-grid stock-overview__grid"><PanelCard title="Acompanhe seu estoque" subtitle="Escolha uma área para continuar a operação."><div class="stock-quick-grid"><NuxtLink to="/estoque?secao=filamentos" class="stock-quick-card"><span class="stock-quick-card__icon stock-quick-card__icon--purple"><UiIcon name="spool" /></span><span><strong>Filamentos</strong><small>{{filaments.length}} cadastrado(s) · {{formatNumber(totalFilamentWeight)}} g disponíveis</small></span><UiIcon name="chevron" :size="16" /></NuxtLink><NuxtLink to="/estoque?secao=produtos" class="stock-quick-card"><span class="stock-quick-card__icon stock-quick-card__icon--green"><UiIcon name="box" /></span><span><strong>Produtos fabricados</strong><small>{{formatNumber(totalProductUnits)}} unidade(s) prontas para venda</small></span><UiIcon name="chevron" :size="16" /></NuxtLink><NuxtLink to="/estoque?secao=movimentacoes" class="stock-quick-card"><span class="stock-quick-card__icon stock-quick-card__icon--blue"><UiIcon name="history" /></span><span><strong>Movimentações</strong><small>{{productMovements.length}} registro(s) de produtos fabricados</small></span><UiIcon name="chevron" :size="16" /></NuxtLink></div></PanelCard><PanelCard title="Alertas de filamentos" subtitle="Reabasteça antes de interromper a produção."><div v-if="!lowFilaments.length" class="empty-state"><p>Nenhum filamento abaixo do mínimo.</p></div><div v-else class="alerts-list"><div v-for="item in lowFilaments.slice(0,5)" :key="item.id" class="alert-row"><span class="alert-row__icon"><UiIcon name="alert" /></span><div><strong>{{item.name}}</strong><small>{{formatNumber(item.remaining)}} g restantes · mínimo {{formatNumber(item.minStock ?? 300)}} g</small></div><NuxtLink class="btn" to="/filamentos">Ver</NuxtLink></div></div></PanelCard></div>
      </div>
      <div v-else-if="section==='filamentos'"><PanelCard title="Estoque de filamentos" subtitle="O saldo e o histórico detalhado continuam disponíveis na tela de filamentos."><div class="stock-summary-list"><div v-for="item in filaments" :key="item.id" class="stock-summary-row"><span class="stock-quick-card__icon stock-quick-card__icon--purple"><UiIcon name="spool" /></span><div><strong>{{item.name}}</strong><small>{{item.material}} · {{item.maker}}</small></div><strong :class="Number(item.remaining) <= Number(item.minStock ?? 300) ? 'money-negative' : 'money-positive'">{{formatNumber(item.remaining)}} g</strong><NuxtLink class="btn" :to="`/filamentos?filament=${item.id}`">Detalhes</NuxtLink></div><div v-if="!filaments.length" class="empty-state"><p>Nenhum filamento cadastrado.</p></div></div></PanelCard></div>
      <div v-else-if="section==='produtos'"><div class="stock-section-head"><div><h2>Produtos fabricados</h2><p>Registre unidades prontas para venda, reserva ou ajuste de saldo.</p></div><NuxtLink class="btn btn--primary" to="/produtos/novo"><UiIcon name="plus" :size="16" />Cadastrar produto</NuxtLink></div><div class="split-layout stock-product-layout"><PanelCard><div class="table-scroll"><table class="data-table"><thead><tr><th>Produto</th><th>SKU</th><th>Disponível</th><th>Reservado</th><th>Status</th></tr></thead><tbody><tr v-for="item in inventory.products" :key="item.id" :class="{selected:String(item.id)===String(selectedProduct?.id)}" @click="selectedProductId=String(item.id)"><td><strong>{{item.name}}</strong></td><td>{{item.sku}}</td><td>{{formatNumber(item.quantity)}} un.</td><td>{{formatNumber(item.reservedQuantity)}} un.</td><td><span class="badge" :class="item.status==='Disponivel'?'badge--green':item.status==='Reservado'?'badge--orange':'badge--red'">{{item.status}}</span></td></tr></tbody></table></div><div v-if="!inventory.products.length" class="empty-state"><p>Cadastre produtos para controlar unidades fabricadas.</p></div></PanelCard><PanelCard title="Registrar produção" :subtitle="selectedProduct ? `Atualizando: ${selectedProduct.name}` : 'Selecione um produto na tabela.'"><div v-if="selectedProduct" class="form-grid"><div class="field col-12"><label>Tipo de movimentação</label><select v-model="movement.type"><option value="in">Entrada de produtos fabricados</option><option value="out">Saída, venda ou descarte</option><option value="adjustment">Ajustar saldo atual</option></select></div><div class="field col-6"><label>{{movement.type==='adjustment'?'Novo saldo':'Quantidade'}} (un.)</label><input v-model.number="movement.quantity" type="number" min="0.01" step="1"></div><div class="field col-6"><label>Saldo atual</label><div class="stat-box"><strong>{{formatNumber(selectedProduct.quantity)}} un.</strong></div></div><div class="field col-12"><label>Motivo obrigatório</label><input v-model="movement.reason" maxlength="240" placeholder="Produção, venda, cancelamento ou descarte"></div><div class="col-12"><button class="btn btn--primary btn--wide" :disabled="saving" @click="saveMovement">{{saving?'Registrando...':'Registrar movimentação'}}</button></div></div><div v-else class="empty-state"><p>Cadastre um produto e selecione-o para registrar unidades.</p></div></PanelCard></div></div>
      <div v-else><PanelCard title="Movimentações de produtos fabricados" subtitle="Histórico auditável de entradas, saídas e ajustes de produtos prontos."><div v-if="!productMovements.length" class="empty-state"><p>Nenhuma movimentação de produto registrada.</p></div><div v-else class="movement-list"><div v-for="item in productMovements" :key="item.id" class="movement-row"><span :class="item.type==='out'?'money-negative':'money-positive'">{{item.type==='out'?'-':item.type==='in'?'+':'='}}{{formatNumber(item.quantity)}} un.</span><div><strong>{{item.resourceName || item.productName}}</strong><small>{{item.reason}} · saldo {{formatNumber(item.resultingQuantity)}} un. · {{new Date(item.createdAt).toLocaleString('pt-BR')}}</small></div></div></div></PanelCard></div>
    </template>
  </div>
</template>

<style scoped>
.stock-tabs{display:flex;gap:4px;flex-wrap:wrap;margin:0 0 16px;padding:4px;border:1px solid var(--line);border-radius:10px;background:#f7f9fc}.stock-tabs a{padding:9px 14px;border-radius:7px;color:var(--muted);font-size:12px;font-weight:650}.stock-tabs a:hover,.stock-tabs a.active{background:#fff;color:var(--blue);box-shadow:0 2px 6px rgba(20,45,85,.08)}.stock-loading{min-height:180px}.stock-overview__grid{grid-template-columns:1.2fr .8fr;margin-top:14px}.stock-quick-grid{display:grid;gap:9px}.stock-quick-card{display:flex;align-items:center;gap:11px;padding:13px;border:1px solid var(--line);border-radius:10px;color:inherit}.stock-quick-card:hover{border-color:#a9c8ff;background:#fbfdff}.stock-quick-card>span:nth-child(2){flex:1}.stock-quick-card strong,.stock-quick-card small{display:block}.stock-quick-card small{margin-top:3px;color:var(--muted);font-size:10px}.stock-quick-card__icon{display:grid;place-items:center;width:35px;height:35px;flex:0 0 auto;border-radius:10px}.stock-quick-card__icon--purple{background:#f0eaff;color:#7c3aed}.stock-quick-card__icon--green{background:#e6f8ef;color:#0a9b5f}.stock-quick-card__icon--blue{background:#e8f1ff;color:#1768f2}.stock-summary-list{display:grid;gap:8px}.stock-summary-row{display:flex;align-items:center;gap:12px;padding:11px 0;border-bottom:1px solid #edf1f6}.stock-summary-row:last-child{border-bottom:0}.stock-summary-row>div{flex:1}.stock-summary-row small,.stock-summary-row strong{display:block}.stock-summary-row small{margin-top:3px;color:var(--muted);font-size:10px}.stock-section-head{display:flex;align-items:end;justify-content:space-between;gap:16px;margin-bottom:14px}.stock-section-head h2{margin:0;font-size:20px}.stock-section-head p{margin:5px 0 0;color:var(--muted);font-size:12px}.stock-product-layout{grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr)}.data-table tbody tr.selected{background:#f2f7ff}@media(max-width:800px){.stock-overview__grid,.stock-product-layout{grid-template-columns:1fr}.stock-section-head{align-items:stretch;flex-direction:column}.stock-summary-row{align-items:flex-start;flex-wrap:wrap}.stock-summary-row .btn{margin-left:auto}}
</style>
