<script setup lang="ts">
const { notify } = useUi()
const priceKg=ref(100), weight=ref(150), hours=ref(6), minutes=ref(0), energyEnabled=ref(true), energyRate=ref(.95), watts=ref(110), margin=ref(500)
const round2=(value:number)=>Math.round((value+Number.EPSILON)*100)/100
const costGram=computed(()=>priceKg.value/1000)
const filamentCost=computed(()=>round2(costGram.value*weight.value))
const duration=computed(()=>hours.value+minutes.value/60)
const energyCost=computed(()=>energyEnabled.value?round2((watts.value/1000)*duration.value*energyRate.value):0)
const directCost=computed(()=>round2(filamentCost.value+energyCost.value))
const estimatedProfit=computed(()=>round2(directCost.value*margin.value/100))
const suggestedPrice=computed(()=>round2(directCost.value+estimatedProfit.value))
const viability=computed(()=>margin.value>=300?{title:'Peca viavel',text:'Com essa margem de lucro, sua peca esta viavel e pronta para ser vendida com seguranca.',state:'good'}:margin.value>=100?{title:'Margem baixa',text:'A peca pode ser vendida, mas a margem pode nao compensar riscos e desgaste.',state:'warn'}:{title:'Peca nao recomendada',text:'Revise os custos ou aumente a margem antes de produzir.',state:'bad'})
</script>
<template>
  <div><PageHeader title="Calculadora 3D" subtitle="Simule o custo e a viabilidade de uma peca impressa em 3D antes de vende-la." icon="calculator"/>
    <div class="calculator-layout"><div><div class="form-card"><h2 class="form-card__title"><UiIcon name="spool"/>Filamento</h2><div class="form-grid"><div class="field col-7"><label>Preco do quilo do filamento (R$)</label><input v-model.number="priceKg" type="number" min="0" step=".01"></div><div class="stat-box col-5" style="text-align:center"><small>Custo por grama</small><strong class="money-positive">{{formatCurrency(costGram)}}</strong><small>por grama</small></div></div></div>
      <div class="form-card"><h2 class="form-card__title"><UiIcon name="box"/>Fatiador</h2><div class="form-grid"><div class="field col-6"><label>Quantidade de material usado (g)</label><input v-model.number="weight" type="number"></div><div class="field col-3"><label>Horas</label><input v-model.number="hours" type="number"></div><div class="field col-3"><label>Minutos</label><input v-model.number="minutes" type="number" max="59"></div></div></div>
      <div class="form-card"><h2 class="form-card__title"><UiIcon name="bolt"/>Energia <span style="margin-left:auto;font-size:10px;font-weight:500">Incluir custo de energia?</span><button class="switch" :class="{active:energyEnabled}" @click="energyEnabled=!energyEnabled"/></h2><div v-if="energyEnabled" class="form-grid"><div class="field col-6"><label>Taxa de energia (R$/kWh)</label><input v-model.number="energyRate" type="number" step=".01"></div><div class="field col-6"><label>Consumo medio da impressora (W)</label><input v-model.number="watts" type="number"></div></div><div v-else class="info-note"><UiIcon name="info"/>A energia nao sera considerada nesta simulacao.</div></div>
      <div class="form-card"><h2 class="form-card__title"><UiIcon name="target"/>Lucro</h2><div class="form-grid"><div class="field col-6"><label>Margem de lucro desejada (%)</label><input v-model.number="margin" type="number"></div><div class="info-note col-6"><UiIcon name="info" :size="17"/>Recomendamos uma margem entre 300% e 500% para cobrir custos fixos e riscos de producao.</div></div></div><div style="display:flex;gap:10px;margin-top:12px"><button class="btn btn--primary" style="flex:1" @click="notify('Simulacao recalculada com sucesso')"><UiIcon name="calculator"/>Calcular</button><button class="btn" style="flex:1" @click="notify('Simulacao salva nesta sessao')"><UiIcon name="save"/>Salvar simulacao</button></div></div>
      <div class="calculator-results"><div class="calculator-results__head"><UiIcon name="trend" :size="34"/><div><h2>Resultado da Simulacao</h2><p>Confira o resumo dos custos e o preco sugerido para sua peca.</p></div></div><div class="result-grid"><div class="result-card"><div class="result-card__label"><UiIcon name="spool"/>Custo do Filamento</div><strong>{{formatCurrency(filamentCost)}}</strong><small>{{weight}} g × {{formatCurrency(costGram)}}</small></div><div class="result-card"><div class="result-card__label"><UiIcon name="bolt"/>Custo de Energia</div><strong>{{formatCurrency(energyCost)}}</strong><small v-if="energyEnabled">{{(watts/1000*duration).toFixed(2)}} kWh × {{formatCurrency(energyRate)}}</small><small v-else>Nao considerada</small></div><div class="result-card result-card--blue"><div class="result-card__label"><UiIcon name="wallet"/>Custo Total Direto</div><strong>{{formatCurrency(directCost)}}</strong><small>Filamento + Energia</small></div><div class="result-card result-card--purple"><div class="result-card__label"><UiIcon name="target"/>Margem Aplicada</div><strong>{{margin}}%</strong><small>Sobre o custo total</small></div><div class="result-card"><div class="result-card__label"><UiIcon name="chart"/>Lucro Estimado</div><strong>{{formatCurrency(estimatedProfit)}}</strong><small>Custo total × {{(margin/100).toFixed(2)}}</small></div><div class="result-card result-card--highlight"><div class="result-card__label"><UiIcon name="tag"/>Preco de Venda Sugerido</div><strong>{{formatCurrency(suggestedPrice)}}</strong><small>Custo total + lucro estimado</small></div></div><div class="viability" :style="viability.state==='warn'?{borderColor:'#f5a623',color:'#b66808',background:'#fffaf0'}:viability.state==='bad'?{borderColor:'#ef4444',color:'#c12c35',background:'#fff5f5'}:{}"><span class="viability__icon"><UiIcon :name="viability.state==='good'?'check':'alert'"/></span><div><h3>{{viability.title}}</h3><p>{{viability.text}}</p></div></div><NuxtLink class="btn btn--success btn--wide" style="margin-top:14px" to="/produtos/novo"><UiIcon name="box"/>Criar produto</NuxtLink></div>
    </div>
  </div>
</template>
