<script setup lang="ts">
const { orders, products, expenses }=useAppData()
const { notify }=useUi()
const type=ref('Vendas'),format=ref('CSV')
const download=()=>{
  const data=type.value==='Vendas'?orders.value:type.value==='Produtos'?products.value:expenses.value
  let content='',mime='',extension=''
  if(format.value==='CSV'){const keys=Object.keys(data[0]||{});content=[keys.join(';'),...data.map(row=>keys.map(k=>String((row as any)[k])).join(';'))].join('\n');mime='text/csv';extension='csv'}else{content=`<?xml version="1.0" encoding="UTF-8"?><dados>${data.map(row=>`<registro>${Object.entries(row).map(([k,v])=>`<${k}>${String(v)}</${k}>`).join('')}</registro>`).join('')}</dados>`;mime='application/xml';extension='xml'}
  const blob=new Blob([content],{type:`${mime};charset=utf-8`});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`printflow-${type.value.toLowerCase()}.${extension}`;a.click();URL.revokeObjectURL(url);notify('Arquivo exportado com sucesso')
}
</script>
<template><div><PageHeader title="Exportacoes" subtitle="Exporte seus dados para analise, contabilidade ou integracoes."/><div class="metrics-grid metrics-grid--4"><MetricCard label="Exportacoes no Mes" value="12" icon="download" change="3,2%" note="vs. mes anterior"/><MetricCard label="Ultimo Arquivo" value="Vendas.csv" icon="receipt" change="Hoje, 09:42" color="green"/><MetricCard label="Registros Disponiveis" value="1.284" icon="chart" change="Atualizados agora" color="purple"/><MetricCard label="Formatos" value="CSV e XML" icon="settings" change="Prontos para uso" color="orange"/></div><div class="dashboard-grid" style="grid-template-columns:.8fr 1.2fr"><PanelCard title="Nova Exportacao" subtitle="Escolha quais dados deseja baixar."><div class="form-grid"><div class="field col-12"><label>Tipo de relatorio</label><select v-model="type"><option>Vendas</option><option>Produtos</option><option>Despesas</option></select></div><div class="field col-6"><label>Periodo inicial</label><input type="date" value="2024-05-01"></div><div class="field col-6"><label>Periodo final</label><input type="date" value="2024-05-31"></div><div class="field col-12"><label>Formato</label><div style="display:flex;gap:8px"><button v-for="f in ['CSV','XML']" :key="f" class="btn" :class="{'btn--primary':format===f}" @click="format=f">{{f}}</button></div></div><div class="col-12"><button class="btn btn--primary btn--wide" @click="download"><UiIcon name="download"/>Gerar e baixar arquivo</button></div></div></PanelCard><PanelCard title="Historico de Exportacoes"><div class="table-scroll"><table class="data-table"><thead><tr><th>Arquivo</th><th>Tipo</th><th>Periodo</th><th>Registros</th><th>Gerado em</th><th>Status</th></tr></thead><tbody><tr v-for="(x,i) in [{n:'vendas-maio.csv',t:'Vendas',r:284,d:'Hoje, 09:42'},{n:'produtos-ativos.xml',t:'Produtos',r:76,d:'Ontem, 16:18'},{n:'despesas-maio.csv',t:'Despesas',r:24,d:'30/05, 10:05'}]" :key="x.n"><td><strong>{{x.n}}</strong></td><td>{{x.t}}</td><td>01/05 - 31/05</td><td>{{x.r}}</td><td>{{x.d}}</td><td><span class="badge badge--green">Concluido</span></td></tr></tbody></table></div></PanelCard></div></div></template>
