<script setup lang="ts">
const { filaments } = useAppData()
const { notify } = useUi()
const selectedIndex = ref(0)
const selected = computed(() => filaments.value[selectedIndex.value])
const pieceWeight = ref(180)
const pieceCost = computed(() => selected.value.cost / selected.value.initial * pieceWeight.value)
const badgeClass = (s:string) => s==='Em estoque'?'badge--green':s==='Atencao'?'badge--orange':'badge--red'
</script>
<template>
  <div><PageHeader title="Filamentos" subtitle="Gerencie seu estoque de filamentos e mantenha o controle de custos por grama."><button class="btn btn--primary" @click="notify('Novo filamento pode ser cadastrado nesta demonstracao','info')"><UiIcon name="plus" :size="16"/>Novo Filamento</button></PageHeader>
    <div class="metrics-grid metrics-grid--5"><MetricCard label="Rolos em Estoque" value="38" icon="spool" change="11,8%" note="vs. mes anterior"/><MetricCard label="Custo Total em Estoque" value="R$ 2.834,65" icon="money" change="9,6%" note="vs. mes anterior" color="green"/><MetricCard label="Custo Medio por Grama" value="R$ 0,072" icon="calculator" change="4,3%" note="vs. mes anterior" color="purple" negative/><MetricCard label="Material Mais Usado" value="PLA" icon="chart" change="62,4% do total" color="orange"/><MetricCard label="Alertas de Baixo Estoque" value="4" icon="alert" change="rolos abaixo do minimo" color="red"/></div>
    <div class="filters"><div v-for="f in ['Fabricante','Material','Cor','Tipo','Status']" :key="f" class="field"><label>{{f}}</label><select><option>Todos</option></select></div><button class="btn"><UiIcon name="close" :size="15"/>Limpar filtros</button></div>
    <div class="split-layout"><PanelCard><div class="table-scroll"><table class="data-table"><thead><tr><th></th><th>Nome</th><th>Fabricante</th><th>Material</th><th>Tipo</th><th>Cor</th><th>Peso Inicial</th><th>Peso Restante</th><th>Custo</th><th>Custo/g</th><th>Fornecedor</th><th>Compra</th><th>Status</th></tr></thead><tbody><tr v-for="(f,i) in filaments" :key="f.name" :class="{selected:selectedIndex===i}" @click="selectedIndex=i"><td><input type="radio" :checked="selectedIndex===i"></td><td><div class="table-product"><span class="product-thumb" style="border-radius:50%"><UiIcon name="spool" :size="28"/></span><strong>{{f.name}}</strong></div></td><td>{{f.maker}}</td><td>{{f.material}}</td><td>{{f.type}}</td><td><span style="display:flex;align-items:center;gap:6px"><i class="dot" :style="{background:f.colorHex,border:'1px solid #ccd3df'}"/>{{f.color}}</span></td><td>{{formatNumber(f.initial)}} g</td><td :class="f.remaining<300?'money-negative':f.remaining<500?'money-positive':''">{{formatNumber(f.remaining)}} g</td><td>{{formatCurrency(f.cost)}}</td><td>R$ {{(f.cost/f.initial).toFixed(3).replace('.',',')}}</td><td>{{f.supplier}}</td><td>{{f.date}}</td><td><span class="badge" :class="badgeClass(f.status)">{{f.status}}</span></td></tr></tbody></table></div><div class="table-footer"><span>Mostrando 1 a 5 de 38 filamentos</span><div class="pagination"><button class="page-btn active">1</button><button class="page-btn">2</button><button class="page-btn">3</button><button class="page-btn">4</button></div></div></PanelCard><aside><div class="detail-card"><div class="detail-card__head"><span class="product-thumb" style="border-radius:50%"><UiIcon name="spool" :size="45"/></span><div><h3>{{selected.name}}</h3><p>Fabricante: {{selected.maker}}</p><p>Material: {{selected.material}}</p><p>Peso restante: <b class="money-negative">{{selected.remaining}} g</b></p></div></div></div><PanelCard title="Calculadora de Custo por Grama" style="margin-top:12px"><div class="form-grid"><div class="field col-6"><label>Custo por grama</label><div class="stat-box"><strong>R$ {{(selected.cost/selected.initial).toFixed(3).replace('.',',')}}</strong></div></div><div class="field col-6"><label>Peso de uma peca</label><input v-model.number="pieceWeight" type="number"><strong class="money-positive">= {{formatCurrency(pieceCost)}}</strong></div></div></PanelCard></aside></div>
    <div class="dashboard-grid" style="grid-template-columns:1fr 1fr 1fr;margin-top:12px"><PanelCard title="Distribuicao por Material"><DonutChart :segments="[{label:'PLA',value:62.4,color:'#1768f2'},{label:'PETG',value:18.7,color:'#2fb4c2'},{label:'ASA',value:10.9,color:'#f6ad2e'},{label:'Outros',value:8,color:'#7c3aed'}]" total="38 rolos"/></PanelCard><PanelCard title="Peso Total em Estoque"><div class="empty-state" style="min-height:170px"><div><div class="empty-state__icon"><UiIcon name="spool"/></div><h3>23,45 kg</h3><p>Rolos cheios equivalem a aproximadamente 31,3 kg.</p></div></div></PanelCard><PanelCard title="Alertas e Recomendacoes"><div class="alerts-list"><div class="alert-row"><span class="alert-row__icon"><UiIcon name="alert"/></span><div><strong>PLA Preto proximo do fim</strong><small>Apenas 180 g restantes</small></div><span class="badge badge--orange">Repor agora</span></div><div class="alert-row"><span class="alert-row__icon"><UiIcon name="bolt"/></span><div><strong>TPU Azul com estoque baixo</strong><small>Somente 260 g restantes</small></div><span class="badge">Ver detalhes</span></div></div></PanelCard></div>
  </div>
</template>
