<script setup lang="ts">
const { printers } = useAppData()
const { notify } = useUi()
const selectedIndex = ref(0)
const selected = computed(() => printers.value[selectedIndex.value])
const energyCost = computed(() => selected.value.power/1000*82*.68)
const badgeClass=(s:string)=>s==='Disponivel'?'badge--green':s==='Em Manutencao'?'badge--orange':''
</script>
<template>
  <div><PageHeader title="Impressoras" subtitle="Gerencie suas impressoras 3D, acompanhe o status e o desempenho operacional."><button class="btn btn--primary" @click="notify('Cadastro de impressora aberto','info')"><UiIcon name="plus"/>Nova Impressora</button></PageHeader>
    <div class="metrics-grid metrics-grid--5"><MetricCard label="Impressoras Ativas" value="12" icon="printer" change="9,1%" note="vs. mes anterior" color="green"/><MetricCard label="Em Impressao" value="6" icon="play" change="20,0%" note="vs. mes anterior"/><MetricCard label="Em Manutencao" value="2" icon="wrench" change="33,3%" note="vs. mes anterior" color="orange" negative/><MetricCard label="Horas Acumuladas" value="1.248 h" icon="clock" change="18,7%" note="vs. mes anterior" color="purple"/><MetricCard label="Custo Medio de Energia" value="R$ 0,68" icon="bolt" change="4,2%" note="vs. mes anterior" color="cyan" negative/></div>
    <div class="split-layout" style="grid-template-columns:minmax(0,1fr) 390px"><div><div class="filters"><div v-for="f in ['Status','Fabricante','Modelo']" :key="f" class="field"><label>{{f}}</label><select><option>Todos</option></select></div><button class="btn"><UiIcon name="close"/>Limpar filtros</button></div><PanelCard><div class="table-scroll"><table class="data-table"><thead><tr><th></th><th>Nome</th><th>Fabricante</th><th>Modelo</th><th>Data de Aquisicao</th><th>Potencia</th><th>Horas Acumuladas</th><th>Status</th><th>Ultima Manutencao</th></tr></thead><tbody><tr v-for="(p,i) in printers" :key="p.code" :class="{selected:i===selectedIndex}" @click="selectedIndex=i"><td><input type="radio" :checked="i===selectedIndex"></td><td><div class="table-product"><span class="product-thumb"><UiIcon name="printer" :size="30"/></span><div><strong>{{p.name}}</strong><small>{{p.code}}</small></div></div></td><td>{{p.maker}}</td><td>{{p.model}}</td><td>{{p.acquired}}</td><td>{{p.power}} W</td><td>{{p.hours}} h</td><td><span class="badge" :class="badgeClass(p.status)">{{p.status}}</span></td><td>{{p.maintenance}}</td></tr></tbody></table></div><div class="table-footer"><span>Mostrando 1 a 6 de 12 impressoras</span><div class="pagination"><button class="page-btn active">1</button><button class="page-btn">2</button></div></div></PanelCard></div><aside class="detail-card"><div class="detail-card__head"><span class="product-thumb" style="width:100px;height:100px"><UiIcon name="printer" :size="65"/></span><div><h3>{{selected.name}} <span class="badge badge--green">{{selected.status}}</span></h3><p>Codigo: {{selected.code}}</p><p>Fabricante: {{selected.maker}}</p><p>Modelo: {{selected.model}}</p><p>Nº de Serie: {{selected.serial}}</p></div></div><div class="detail-card__body"><div class="stat-strip"><div class="stat-box"><small>Potencia</small><strong>{{selected.power}} W</strong></div><div class="stat-box"><small>Consumo Medio</small><strong>{{(selected.power/1000).toFixed(2)}} kWh</strong></div><div class="stat-box"><small>Horas (Mes)</small><strong>82 h</strong></div><div class="stat-box"><small>Custo kWh</small><strong>R$ 0,68</strong></div></div><div class="form-card" style="margin-top:12px"><h3 style="margin:0;font-size:12px">Calculo de Custo de Energia</h3><p style="color:var(--muted);font-size:9px">Potencia (kW) × Tempo (h) × Valor do kWh</p><div class="summary-box"><div class="detail-list__row"><span>Custo estimado mensal</span><strong class="money-positive">{{formatCurrency(energyCost)}}</strong></div></div></div><div class="form-card"><h3 style="margin:0 0 10px;font-size:12px">Informacoes Adicionais</h3><div class="detail-list"><div class="detail-list__row"><span>Localizacao</span><strong>Lab Principal</strong></div><div class="detail-list__row"><span>Volume de Impressao</span><strong>220 × 220 × 250 mm</strong></div><div class="detail-list__row"><span>Filamento Padrao</span><strong>PLA</strong></div></div></div></div></aside></div>
  </div>
</template>
