<script setup lang="ts">
type ReportFilters = { periodStart: string; periodEnd: string; grouping: 'day' | 'week' | 'month'; marketplace: string; product: string; category: string; channel: string }
const { exportFinancialReport, products, orders, expenses } = useAppData()
const { notify } = useUi()
const route = useRoute()
const today = new Date()
const filters = reactive<ReportFilters>({ periodStart: `${today.getFullYear()}-01-01`, periodEnd: today.toISOString().slice(0, 10), grouping: 'month', marketplace: 'Todos', product: 'Todos', category: 'Todos', channel: 'Todos' })
const exportFormat = ref<'csv' | 'xlsx'>('xlsx')
const exporting = ref(false)
const reportSection = computed(() => { const section = String(route.query.secao || 'financeiro'); return ['financeiro', 'produtos', 'estoque', 'historico'].includes(section) ? section : 'financeiro' })
const marketplaceOptions = computed(() => ['Todos', ...new Set(orders.value.map(item => item.marketplace || 'Sem marketplace'))])
const productOptions = computed(() => ['Todos', ...new Set(products.value.map(item => item.name))])
const categoryOptions = computed(() => ['Todos', ...new Set(expenses.value.map(item => item.category || 'Sem categoria'))])
const exportReport = async () => { if (filters.periodStart > filters.periodEnd || exporting.value) return notify('Informe um período válido para exportar.'); exporting.value = true; try { const content = await exportFinancialReport({ from: filters.periodStart, to: filters.periodEnd, marketplace: filters.marketplace === 'Todos' ? '' : filters.marketplace, product: filters.product === 'Todos' ? '' : filters.product, category: filters.category === 'Todos' ? '' : filters.category, channel: filters.channel === 'Todos' ? '' : filters.channel, format: exportFormat.value }); const url = URL.createObjectURL(content); const link = document.createElement('a'); link.href = url; link.download = `printflow-relatorio-${filters.periodStart}-${filters.periodEnd}.${exportFormat.value}`; link.click(); URL.revokeObjectURL(url); notify('Relatório exportado com sucesso.') } catch (error: any) { notify(error?.data?.error || error?.message || 'Não foi possível exportar o relatório.') } finally { exporting.value = false } }
</script>
<template><div><PageHeader title="Relatórios completos" subtitle="Analise dados reais do período e exporte as informações da sua empresa."><div class="report-actions"><select v-model="exportFormat" class="report-export-format" aria-label="Formato da exportação"><option value="xlsx">XLSX</option><option value="csv">CSV</option></select><button class="btn" :disabled="exporting" @click="exportReport"><UiIcon name="download"/>{{ exporting ? 'Gerando...' : 'Exportar relatório' }}</button></div></PageHeader><section class="report-filters" aria-label="Filtros dos relatórios e da exportação"><div class="report-filters__heading"><strong>Período e filtros</strong><span>Os mesmos filtros são usados na análise e no arquivo exportado.</span></div><div class="filters"><div class="field"><label>Início</label><input v-model="filters.periodStart" type="date"></div><div class="field"><label>Fim</label><input v-model="filters.periodEnd" type="date"></div><div class="field"><label>Agrupamento</label><select v-model="filters.grouping"><option value="month">Mensal</option><option value="week">Semanal</option><option value="day">Diário</option></select></div><div class="field"><label>Marketplace</label><select v-model="filters.marketplace"><option v-for="item in marketplaceOptions" :key="item">{{item}}</option></select></div><div class="field"><label>Canal de venda</label><select v-model="filters.channel"><option>Todos</option><option>Diretas</option><option>Marketplace</option></select></div><div class="field"><label>Produto</label><select v-model="filters.product"><option v-for="item in productOptions" :key="item">{{item}}</option></select></div><div class="field"><label>Categoria de despesa</label><select v-model="filters.category"><option v-for="item in categoryOptions" :key="item">{{item}}</option></select></div></div></section><LazyRelatoriosRelatorioFinanceiro v-if="reportSection === 'financeiro'" v-model:filters="filters"/><LazyRelatoriosRelatorioProdutos v-else-if="reportSection === 'produtos'" :filters="filters"/><LazyRelatoriosRelatorioEstoque v-else-if="reportSection === 'estoque'" :period-start="filters.periodStart" :period-end="filters.periodEnd"/><LazyRelatoriosRelatorioHistorico v-else :period-start="filters.periodStart" :period-end="filters.periodEnd"/></div></template>
<style scoped>.report-actions{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:8px;max-width:100%}.report-export-format{min-width:76px;border:1px solid #d8deea;border-radius:8px;padding:0 8px;background:#fff}.report-filters{margin:0 0 18px;padding:16px 18px;border:1px solid #dce4f0;border-radius:14px;background:#fff}.report-filters__heading{display:flex;align-items:baseline;gap:9px;margin-bottom:12px}.report-filters__heading strong{color:#172033}.report-filters__heading span{font-size:12px;color:#687386}@media(max-width:780px){.report-actions{width:100%;justify-content:flex-start}.report-actions .btn{flex:1;justify-content:center}.report-export-format{min-height:38px}.report-filters{padding:14px}.report-filters__heading{align-items:flex-start;flex-direction:column;gap:3px}}</style>
